spring:
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: null
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console