mqtt:
  broker:
    url: tcp://192.168.1.6:61613
    username: admin
    password: password
  consumer:
    clientId: test${random.int[1024,65536]}
    topic: greetings/
  provider:
    clientId: test${random.int[1024,65536]}
    topic: greetings/
camel:
  springboot:
    typeConversion: false
    xmlRoutes: classpath:camel-routes/**.xml
scheduled: 0/1 * * * * ?
runtime: 1
server:
  port: 8081